from django.urls import path, include
from . import views
from . import views_classes

urlpatterns = [
    path("", views.index, name="index"),
    path("customers", views.get_customers, name="customer_list"),
    path("customers2/", views_classes.CustomerListView.as_view(), name="customers2"),
    path("customers/<int:customer_id>", views.get_customer_details, name="customer_details"),
    path("customers2/<int:pk>", views_classes.CustomerDetailView.as_view(), name="customers2_detail"),
    path("customers/add", views.add_customer, name="add_customer"),
    path("customers2/add", views_classes.CustomerCreateView.as_view(), name="customers2_add"),
    path("customers/<int:customer_id>/update", views.update_customer, name="customer_update"),
    # path("products", views.get_products, name="product_list"),
    path("products", views_classes.ProductListView.as_view(), name="product_list"),
    # path("products/<int:product_id>", views.get_product_details, name="product_details"),
    path("products/<int:pk>", views_classes.ProductDetailView.as_view(), name="product_details"),
    # path("products/add", views.add_product, name="product_add"),
    path("products/add", views_classes.ProductCreateView.as_view(), name="product_add"),
    # path("products/<int:product_id>/update", views.update_product, name="product_update"),
    path("products/<int:pk>/update", views_classes.ProductUpdateView.as_view(), name="product_update"),
    # path("products/<int:product_id>/delete", views.delete_product, name="product_delete"),
    path("products/<int:pk>/delete", views_classes.ProductDeleteView.as_view(), name="product_delete"),
    path("products/<int:product_id>/buy", views.buy_product, name="product_buy"),
    path("products/<int:product_id>/add_to_cart", views.add_product_to_cart, name="add_to_cart"),
    path("cart/", views.cart_details, name="cart_details"),
    path("cart/delete/<int:cart_item_id>", views.remove_product_from_cart, name="remove_from_cart"),
    path("cart/update/<int:cart_item_id>", views.update_product_in_cart, name="update_cart"),
    path("cart/checkout/", views.create_purchase, name="create_purchase"),
    path("register/", views.register, name="register"),
    path("page1/", views.page1, name="page1"),
    path("page2/", views.page2, name="page2"),
    # path("set_language_hu/", views.set_language_hu, name="set_language_hu"),
    # path("set_language_en/", views.set_language_en, name="set_language_en"),
    # path("set_language_de/", views.set_language_de, name="set_language_de"),
    # path("set_language/<str:language_code>", views.set_language, name="set_language"),
    path("set_language/", views.set_language2, name="set_language2"),
    path("view1", views_classes.MyView.as_view(), name="view1"),
    path("view2", views_classes.MyTemplateView.as_view(), name="view2"),
]
