# Generated by Django 5.1.7 on 2025-03-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_dte',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
