# Generated by Django 5.1.7 on 2025-04-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_homeaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeaddress',
            options={'verbose_name': 'Home address', 'verbose_name_plural': 'Home addresses'},
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.IntegerField(choices=[(1, 'Magyarország'), (2, 'Ausztria')], default=1)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shopping.customer')),
            ],
            options={
                'verbose_name': 'Customer address',
                'verbose_name_plural': 'Customer addresses',
            },
        ),
    ]
