# Generated by Django 5.1.7 on 2025-04-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_homeaddress_options_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='house_number',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_addresses', to='shopping.customer'),
        ),
    ]
