# Generated by Django 5.1.7 on 2025-04-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
