# Generated by Django 5.1.7 on 2025-04-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_rename_image_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiry_dte',
            new_name='expiry_date',
        ),
    ]
