# Generated by Django 5.1.7 on 2025-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_cartitem_shopingcart_cartitem_shopping_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopingcart',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='shopingcart',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='shopingcart',
            name='products',
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-09 15:42:16.342890'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopingcart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
