# Generated by Django 5.1.7 on 2025-04-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_application', '0005_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='library_application.author'),
        ),
    ]
